- README.md
- languages/ocaml/repl.ml
Enables following:
```ml
(* test.ml *)
let a = 1 + 1;;
print_endline "Loaded";;
```
Running it:
```sh
./prybar-ocaml -i test.ml
```
Some example interaction:
```
OCaml 4.07.0 on Unix
Loaded
-->  a;;
- : int = 2
-->
```
Note how the `a` binding is available in the interactive session.
> Add eval-file behavior for OCaml

- languages/python3/main.go
See https://github.com/replit/prybar/pull/6#pullrequestreview-175641157
Tested that `./prybar-python3 -i` now gives `NameError` for `signal`, but I can still `import` the module without error.
> Remove 'signal' from scope for python

- prybar_assets/elisp/repl.el
* Add project directory to `load-path`, so you can `require` the files in it.
* Redisplay when starting Emacs, which fixes both C-a/C-e malfunctions and also all the text sometimes getting underlined for no discernible reason.
> Improvements for Emacs Lisp

- Dockerfile.dev
- Makefile
- README.md
- extract.sh
- languages/R/main.go
- scripts/docker-install.sh
- scripts/inject.sh
* Fix "Running as root is not recommended" message at container startup. See <https://github.com/ocaml/opam/issues/2575>.
* Add Makefile targets to build and run Docker images, and 'make help' target.
* Reduce number of layers in Dockerfile and improve build time.
* Fix several bugs in Makefile which were causing spurious rebuilds.
* Remove legacy extract.sh script.
* Use HTTPS when downloading libmozjs.
* Improve readability of Dockerfile and Makefile. Split out dependency installation into a separate Bash script.
* Reduce verbosity of application and Docker builds.
* Fix mistake in Cgo configuration for R, although R is still broken because using Cgo with libR requires Go 1.10.5 while Ubuntu Bionic only ships 1.10.4. See <https://github.com/golang/go/issues/27496>.
> Improve developer experience with Docker

- languages/elisp/main.go
- scripts/docker-install.sh
Using `-nw` is necessary if we want to support Emacs 26 from the kelleyk PPA, which is compiled with graphical support and therefore gets tangled up with our X11 support on Repl.it.
> Start Emacs with -nw argument; upgrade from 25 to 26

- .gitignore
- Dockerfile
- Dockerfile.dev
- Makefile
- languages/julia/main.go
- languages/sqlite/compile
- scripts/docker-install.sh
- tests/julia/header.exp
- tests/sqlite/header.exp
This is needed for Python 3.7, which we are upgrading Repl.it to use. Also:
* Install Emacs 26 from official repos instead of PPA.
* Install Julia to /usr/local instead of /usr, and upgrade from 1.1.0 to 1.1.1.
* No longer install m4 and opam.
* Add explanatory comments to Docker install script.
> Update base image from Bionic to Disco

- .gitignore
- Dockerfile
- Dockerfile.dev
- Makefile
- languages/julia/main.go
- languages/sqlite/compile
- scripts/docker-install.sh
- tests/julia/header.exp
- tests/sqlite/header.exp
Reverts replit/prybar#32, which reverted replit/prybar#31. I can merge this once https://github.com/replit/goval/pull/768 is ready to be deployed, which should prevent our CI from failing again.
> Update base image from Bionic to Disco (again)

- languages/elisp/main.go
- scripts/docker-install.sh
* If a file named `Cask` exists, and a command named `cask` is on the `$PATH`, then use `cask exec` to make the Cask dependencies available in the repl. This will be good for interop with UPM / packager3.
* Also, this was literally the first Go code I ever wrote, so I did some cleanup on it.
> prybar-elisp: Automatically use Cask if available

- prybar_assets/elisp/repl.el
This means you can import https://github.com/magit/magit into Repl.it and just be able to `(require 'magit)`, for example. Many large Elisp projects use a `lisp/` subdirectory.
> Add lisp/ subdirectory to load-path

- languages/tcl/main.go
- tests/tcl/invalid_command.exp
In theory, this change should allow error messages to be displayed when they occur when running a Tcl repl.
> Display error message when running a Tcl file

- languages/python3/main.go
- scripts/docker-install.sh
`prybar-python3` should link against Python 3.8 so that we can move to 3.8 on Repl.it.
There was a little gotcha in 3.8 (https://docs.python.org/3.8/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build) which is why I had to change the cgo flag: 
> Add a pkg-config `python-3.8-embed` module to embed Python into an application
> Use Python 3.8

- scripts/docker-install.sh
- tests/julia/header.exp
Bump from 1.1 to 1.3
Polygott is actually on version 1.3 already and the mismatch is causing issues.
> Upgrade Julia version

- languages/julia/main.go
- scripts/docker-install.sh
Polygott currently installs julia under `/usr`, not `/usr/local`. I'm changing prybar to match polygott so `prybar-julia` can find the julia shared libraries.
For whatever reason, even if I make both polygott and prybar install julia under `/usr/local`, `prybar-julia` cannot find `libjulia.so` at runtime.
> install julia under /usr instead of /usr/local

- .circleci/config.yml
Once master successfully builds, we push a tag with the project number and the build number (both increase monotonically). This allows downstream projects (mainly polygott) to depend explicitly on particular versions of prybar.
> Push git tag on successful build of master

- languages/python3/main.go
An embedded python interpreter computes `sys.path` based on the prefix of the interpreter name: https://docs.python.org/3/c-api/init.html#c.Py_SetProgramName
To make sure `sys.path` is set correctly (and the appropriate `sitecustomize.py` is loaded if present) when a virtualenv is activated, the program name needs to start with the virtualenv path. At startup, prybar-python3 looks for the $VIRTUAL_ENV environment variable and, if present, sets the program name to $VIRTUAL_ENV/bin/prybar-python3.
Testing this path requires adding machinery to the prybar tests. I don't want to take the time to add that machinery now, but I have tested this branch in polygott and it does indeed set the correct path.
> prybar-python3 honors $VIRTUAL_ENV

- languages/python3/main.go
While trying to run `pip.main(['install', 'wikipedia'])` from prybar-python3, I saw the following error:
```
ERROR: Error [Errno 2] No such file or directory: '/opt/virtualenvs/python3/bin/prybar-python3' while executing command python setup.py egg_info
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/opt/virtualenvs/python3/bin/prybar-python3'
```
Backing this PR out while I cook up a fix.
Reverts replit/prybar#53
> Revert "prybar-python3 honors $VIRTUAL_ENV"

- languages/nodejs/repl.js
- test_files/global_bug.js
- tests/nodejs/eval_code.exp
- tests/nodejs/global_bug.exp
In the current implementation, `instanceof` fails because we get classes like `Array` and `Object` from a different realm. 
With this, we only copy things that are missing from the context (and the console).
This is implementing https://github.com/replit/goval/pull/1419
> Better global support

- languages/nodejs/repl.js
- run_tests
- test_files/global_bug.js
- test_files/global_require.js
- test_files/module_patching.js
- tests/nodejs/err.exp
- tests/nodejs/global_bug.exp
- tests/nodejs/module_patching.exp
- tests/nodejs/run_file.exp
When running with an entrypoint, the entry point's globals/context is different from required modules. This breaks some packages such as math.js that rely on instanceof. You can see the bug in the newly added asserts https://github.com/replit/prybar/commit/10c16f9e064d0ec3f522df76276c1f4f5eaf9b2e.
Use the (current) global context when running the file, i.e. `script.runInThisContext`. This change gives us the piece of mind going forward when dealing with the global context. We still patch somethings, like adding `alert`, `confirm`, and `prompt`. We also patch the `global.module` and `global.require` to make sure the context thinks we're in the entrypoint file rather than the `repl.js` file.
I also fixed a bunch of tests that were broken.
> Fix cross module node globals

- prybar_assets/nodejs/input-sync.js
- tests/nodejs/prompt_tty.exp
- tests/nodejs/prompt_tty_bounds.exp
- tests/nodejs/prompt_tty_escapes.exp
thanks to @turbio I found that left+right arrows don't work right.  They didn't work with `readline-sync` either, but the behavior is different (ie, we'll print them back rather than let the pty escape and local echo).
This adds proper support + some tests + replaces `\x1b` with `^` for anything else - which is what the pty would do for `readline-sync`.
> [nodejs prompt/confirm] support left+right arrow keys

- languages/nodejs/repl.js
- test_files/global_bug.js
- test_files/global_bug_submodule.js
- test_files/main_module_scoped_to_global.js
- test_files/main_module_scoped_to_global_submodule.js
- test_files/module_patching.js
- tests/nodejs/main_module_scoped_to_global.exp
TL;DR nodejs-prybar implementation now matches https://github.com/replit/goval/blob/master/images/nodejs/interp.js including the bugs so we can migrate nodejs to prybar without changing any behavior.
We want to start using prybar node on replit, the prybar implementation has a bug where defining a variable in the main file leads to it defined being defined in the global scope. This bug can be seen in the new test `main_module_scoped_to_global` which now passes.
I changed the implementation to use a custom nodejs context instead of using a global context which seems to solve this problem. However, it introduces a new bug where `global`s in the main file are not the same as globals in submodules :eyes:. This is because we inject `require` into the context from the global scope meaning …
> Swap nodejs-prybar some bugs for others

- languages/elisp/main.go
The elisp prybar was trying to get `repl.el` from the wrong directory. Now it relies on `PRYBAR_ASSETS_DIR` as set by Nix.
:thinking: there's probably a better way to do this than an env var...
> Fix elisp prybar asset dir lookup when bundled with Nix

- build-prybar.nix
Noticed sqlite was missing a shared library that is supposed to be LD_PRELOAD'd into the sqlite cli. This compiles it so it ends up in the `prybar_assets` directory in the final built Nix derivation.
> Ensure sqlite shared library is compiled and included in Nix derivation

- languages/sqlite/main.go
Same as https://github.com/replit/prybar/pull/80 but for sqlite
Test plan:
Run `nix run .#prybar-sqlite -- -q -i main.sql` with an example `main.sql`
It doesn't complain about bad path to LD preload lib
> Fix wrong prybar asset dir for sqlite

- flake.nix
Updating nixpkgs updated Node to a new major version in the Nix check phase which broken a test. This pins us to v12.
Note: This is just the version of Node used to run the test, prybar still uses whatever node is in the environment.
> Fix broken test for nodejs

- flake.nix
Using native packages such as tkinter with prybar-python3 doesn't currently work.
```
~$ prybar-python3 -i
Python 3.8.12 (default, Aug 30 2021, 16:42:10) 
[GCC 10.3.0] on linux
--> import turtle
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/nix/store/wlhmpa2qk786ddp05ahv3jjlds6d44a5-python3-3.8.12/lib/python3.8/turtle.py", line 107, in <module>
import tkinter as TK
File "/nix/store/wlhmpa2qk786ddp05ahv3jjlds6d44a5-python3-3.8.12/lib/python3.8/tkinter/__init__.py", line 36, in <module>
import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```
Switching to python38Full instead of just python38 solves the problem.
```
~/turtle-test/prybar$ nix-build -A prybar-python3 …
```
> Use python38Full in prybar-python3 so native packages work

- prybar_assets/nodejs/module-context-hook.js
https://app.asana.com/0/0/1202058950801330
To avoid confusing errors in stack traces, we would re-run compiled code if it error-ed to avoid syntax errors on lines that don't  exist.
This caused the following code to run twice since "compile" in nodejs is "compile and run."
```js
console.log('hi');
throw new Error('blah');
```
Since the only errors we care about are syntax errors, we'll instead use `compileFunction` from `vm` to validate the syntax - if it fails, we'll compile the original code (to get an appropriate error); otherwise we'll compile the  code with our footer (at this point we don't care if the code fails since the callsites will be on the correct lines).
> [nodejs] don't run code twice on error

- languages/lua/lua.c
- languages/lua/lua_test.go
- languages/lua/testdata/test.lua
- test.lua
Why
===
_Describe what prompted you to make this change, link relevant resources: Asana tasks, Canny report, Slack discussions...etc_
Fixes intermittent Lua crashes described in [this asana task](https://app.asana.com/0/home/1202058573462454/1202272228116397)
I *believe* this crash is triggered due to reading garbage, and only intermittently possibly because of different allocation patterns.
What changed
============
_Describe what changed to a level of detail that someone with no context with your PR could be able to review it_
- Pass in number of arguments instead of determining them based on the given array shape (which starts reading garbage)
- This is hardcoded to `1` (the filename) and `getargs` only appears to be used from one place. Do we ever actually have any arguments? Why does …
> [Lua] [sus] Fix intermittent Lua crashes

- .prettierrc
I'm undecided if this should be global or not; also if we should commit properly in some better way. 
See #98 for a more localized location. Please feel free to just close either or both of these. 
I did confirm that at least VSCode with prettier installed automatically runs prettier with this file present, even if it isn't local/listed in the dev. dependencies.
> Add global prettier config.

- flake.nix
Forgot to add prybar-python311 to overlay.
> add prybar-python311 to overlay
